export {default as BackTracking} from 'features/algorithms/pages/BackTracking'
export {default as BruteForce} from 'features/algorithms/pages/BruteForce'
export {default as DivideConquer} from 'features/algorithms/pages/DivideAndConquer'
export {default as DP} from 'features/algorithms/pages/DynamicProgramming'
export {default as Greedy} from 'features/algorithms/pages/Greedy'